# Generated by Django 4.1.5 on 2023-01-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_code', models.CharField(max_length=30, null=True)),
                ('nome', models.CharField(max_length=45, null=True)),
                ('sobrenome', models.CharField(blank=True, max_length=45, null=True)),
                ('sexo', models.CharField(choices=[('M', 'masculino'), ('F', 'feminino')], max_length=2, null=True)),
                ('altura', models.FloatField(blank=True, default=None, null=True)),
                ('peso', models.FloatField(blank=True, default=None, null=True)),
                ('nascimento', models.DateTimeField(null=True, verbose_name='Data')),
                ('bairro', models.CharField(max_length=35, null=True)),
                ('cidade', models.CharField(max_length=25, null=True)),
                ('estado', models.CharField(max_length=25, null=True)),
                ('numero', models.DecimalField(decimal_places=0, max_digits=8, null=True)),
                ('arquivo', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
